version: '3.8'

services:
  # MySQL 数据库服务
  mysql:
    image: mysql:8.0.32
    container_name: bhuang-bigmark-mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: big_market
      MYSQL_USER: big_market
      MYSQL_PASSWORD: big_market
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docs/dev-ops/mysql:/docker-entrypoint-initdb.d
    networks:
      - bigmark-network

  # Redis 缓存服务
  redis:
    image: redis:7.0-alpine
    container_name: bhuang-bigmark-redis
    environment:
      TZ: Asia/Shanghai
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bigmark-network
    command: redis-server --appendonly yes --requirepass ""

  # 应用服务
  app:
    image: crpi-wzl2k45d0lxbiagj.cn-shenzhen.personal.cr.aliyuncs.com/bhuang-repo/bhuang-bigmark:latest
    container_name: bhuang-bigmark-app
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/big_market?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_DATABASE: 0
    ports:
      - "8091:8091"
    depends_on:
      - mysql
      - redis
    networks:
      - bigmark-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  bigmark-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local 